# Execute only if it's a PR which comes from dev
name: PR to master
on:
  push:
    branches:
      - master  # No push to master allowed, but I need to listen this event, so I can reject it
  pull_request:
    branches:
      - master  # I allow only PR from dev -> master

jobs:
  #-----------------------------------------------------------------------
  #--- Validate the PR's branch
  #-----------------------------------------------------------------------
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Block direct pushes to master
        # Ensure the push is made only by GitHub bot, meaning on the merge of a PR
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.actor == 'github-actions[bot]'
        run: |
          echo "❌ Direct push to master is not allowed!"
          exit 1

      - name: Enforce PRs to master must come from dev
        if: github.event_name == 'pull_request' && github.base_ref == 'master'
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "❌ PRs to master must come from dev!"
            exit 1
          else
            echo "✅ PR from dev to master authorized."
          fi

  #-----------------------------------------------------------------------
  #--- Test the service
  #-----------------------------------------------------------------------
  test-service:
    runs-on: ubuntu-latest
    needs: validate-branch  # Only runs if validation passes
    if: success()  # Ensures the first job succeeds

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven and Run Tests
        run: |
          chmod +x mvnw
          ./mvnw clean test
